codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
        informational: true  # Don't fail CI if coverage drops slightly
    patch:
      default:
        target: 85%  # Require at least 85% coverage on new code
        threshold: 5%  # Allow up to 5% variation
        base: auto
        informational: false  # Still enforce this one

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true


ignore:
  - "node_modules"
  - "tests"
  - "scripts"
  - "coverage"
  - "coverage-e2e"
  - "coverage-v8"
  - "*.config.js"
  - "playwright.config.js"
  - "vitest.config.js"
