codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "node_modules"
  - "tests"
  - "scripts"
  - "coverage"
  - "coverage-e2e"
  - "coverage-v8"
  - "*.config.js"
  - "playwright.config.js"
  - "vitest.config.js"
